[DEFAULT]
;Default fanpage token được sử dụng để debug ở local.
FANPAGE_TOKEN = EAAFCFHCMLPwBABWdKcc5SN2Sovd273Cwc59m0iFKJ8dQzlXvctph3RHUAfI93T3mPky5zpuqZALfjdmFQXjairTjeg20wOYxWFiH94mPraQ15O7KPZB7dqJRGgJYvE6leSuXJcvsFPrIHPbJsekIkZAouBlMJUrkSaCCMGykg7WRvsS7UO3

;Danh sách những từ hệ thống sẽ thực hiện replace trong câu trả lời của Facebook
GENDER_L = anh/chị;anh/chi
GENDER_U = Anh/Chị;Anh/Chi;Anh/chi;Anh/chị;anh/Chi;anh/Chị

;Thời gian timeout cho thread. Để 4 vì Dialogflow họ giới hạn 5s.
THREAD_TIMEOUT = 4

;Coinfig cho cấu hình cache
;Số items max lưu trong cache
CACHE_MAXSIZE = 1000
;Thời gian sống của 1 item trong cache tính theo giây
CACHE_TTL = 1800
;Hết cấu hình cho cache