version: '3'
services:
  htkh-bot-sme:
    build: .
    volumes:
      - /opt/projects/fulfillment-webhook/:/code/
    stdin_open: true
    env_file:
      - /opt/projects/fulfillment-webhook/config.env
    environment:
      FanpageToken : EAAEsmcY7SkgBACrQH5b8dvZBVwqMZBeWIVN8hVQVgZCLLftdu6Gjq7ZAZCKKf1Nfn3YZAoErGYn4TmH4xA7Wv6s2X52ERqNxGjAMUAICFJ4pomdAS28GlGYl8ZA059ocwaDsEimBWfWuYYzsZA8ULRgVfpMMVKrNuFI787pRozYIvTjeyiW5gtLWgBYGkvAEAuEZD
      DFClientToken : dff9b6906ff94bed830a10697ec4e658
    tty: true
    restart: always
    ports:
      - 8904:5000
    container_name: "htkh-bot-sme"

  htkh-bot-mimosa:
    build: .
    volumes:
      - /opt/projects/fulfillment-webhook/:/code/
    stdin_open: true
    env_file:
      - /opt/projects/fulfillment-webhook/config.env
    environment:
      FanpageToken : EAAEsmcY7SkgBACrQH5b8dvZBVwqMZBeWIVN8hVQVgZCLLftdu6Gjq7ZAZCKKf1Nfn3YZAoErGYn4TmH4xA7Wv6s2X52ERqNxGjAMUAICFJ4pomdAS28GlGYl8ZA059ocwaDsEimBWfWuYYzsZA8ULRgVfpMMVKrNuFI787pRozYIvTjeyiW5gtLWgBYGkvAEAuEZD
      DFClientToken : dff9b6906ff94bed830a10697ec4e658
    tty: true
    restart: always
    ports:
      - 8900:5000
    container_name: "htkh-bot-mimosa"

  htkh-bot-cukcuk:
    build: .
    volumes:
      - /opt/projects/fulfillment-webhook/:/code/
    env_file:
      - /opt/projects/fulfillment-webhook/config.env
    stdin_open: true
    environment:
      FanpageToken : EAACPPDsQaS0BAExsREUHTkstZBZArAzIl2j1maWqp1rA7UZCrV1H02tzaprt9VfU4zy6KUdB7J1Bf7gyF0hkEphFAdYKq3PWEtiZBmEOO7ZAGjpH1LifSYiYiczJnpQoggSMyMQSQb0ZAlAc7bdB0MaijYoqpDW74C9nYzrAP7UwZDZD
      DFClientToken : 22687af5bfdf43f5aa347846f59b4c72
    tty: true
    restart: always
    ports:
      - 8901:5000
    container_name: "htkh-bot-cukcuk"

